admin_index:
  path:     /
  defaults: { _controller: RESERVATIONBundle:Admin:index }


admin_accueil:
  path:     /accueil
  defaults: { _controller: RESERVATIONBundle:Admin:accueil }

admin_reservation:
  path:     /reservation
  defaults: { _controller: RESERVATIONBundle:Admin:reservation }


admin_listebien:
  path:     /listebien
  defaults: { _controller: RESERVATIONBundle:Admin:listebien }


test_ajax:
  path:     /test_ajax
  defaults: { _controller: RESERVATIONBundle:Admin:test_ajax }